"""Demand curves used by the driven fee-market replay.

The dynamic benchmark uses the independent isoelastic estimates reproduced in
publication notebook ``resource_demand_and_glamsterdam_equilibrium/03``. A matrix version is provided as an explicit coupling
sensitivity: off-diagonal entries describe how demand for resource ``i``
changes when the price of resource ``j`` changes.

All quantities returned here are already in candidate-world resource gas.
The public demand name ``data`` is translated to the mechanism's internal
name ``bandwidth`` only at the replay boundary.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Mapping, Protocol

DEMAND_RESOURCES = ("execution", "data", "state")


class MeteredDemandModel(Protocol):
    """A fee-responsive source of offered resource gas."""

    def quantities(
        self,
        base_fees_wei: Mapping[str, float],
    ) -> dict[str, float]: ...


@dataclass(frozen=True)
class BundleDemandEvaluation:
    """Component-aware result from the bundle-priced EIP-7999 demand model."""

    offered_gas: Mapping[str, float]
    parent_quantities: Mapping[str, float]
    parent_prices_wei: Mapping[str, float]
    static_data_gas: float
    execution_bal_gas: float
    state_bal_gas: float
    effective_execution_bal_intensity: float
    access_shock: float = 1.0

    @property
    def total_bal_gas(self) -> float:
        return float(self.execution_bal_gas) + float(self.state_bal_gas)

    def diagnostics(self) -> dict[str, float]:
        return {
            "execution_parent_quantity": float(self.parent_quantities["execution"]),
            "state_parent_quantity": float(self.parent_quantities["state"]),
            "execution_parent_price_wei": float(self.parent_prices_wei["execution"]),
            "state_parent_price_wei": float(self.parent_prices_wei["state"]),
            "static_data_gas": float(self.static_data_gas),
            "execution_bal_gas": float(self.execution_bal_gas),
            "state_bal_gas": float(self.state_bal_gas),
            "total_bal_gas": float(self.total_bal_gas),
            "effective_execution_bal_intensity": float(
                self.effective_execution_bal_intensity
            ),
            "access_shock": float(self.access_shock),
        }


def _require_resource_mapping(
    values: Mapping[str, float],
    *,
    label: str,
    allow_zero: bool,
) -> None:
    for resource in DEMAND_RESOURCES:
        if resource not in values:
            raise ValueError(f"{label} is missing {resource!r}")
        value = float(values[resource])
        if not math.isfinite(value):
            raise ValueError(f"{label}[{resource!r}] must be finite")
        if value < 0 or (value == 0 and not allow_zero):
            qualifier = "non-negative" if allow_zero else "positive"
            raise ValueError(f"{label}[{resource!r}] must be {qualifier}")


@dataclass(frozen=True)
class IndependentIsoelasticDemand:
    """Three independently price-responsive isoelastic demand curves.

    For each resource ``i``::

        q_i(p_i) = q_i_ref * (p_i / p_i_ref) ** (-epsilon_i)

    ``anchor_metered_gas`` is gas per block under the candidate metering, not
    historical receipt gas.  ``reference_base_fees_wei`` must therefore use
    the same transport convention as the anchor (archived notebook 2.0 preserves the
    historical effective price when constructing these values).
    """

    anchor_metered_gas: Mapping[str, float]
    reference_base_fees_wei: Mapping[str, float]
    elasticities: Mapping[str, float]

    def __post_init__(self) -> None:
        _require_resource_mapping(
            self.anchor_metered_gas,
            label="anchor_metered_gas",
            allow_zero=False,
        )
        _require_resource_mapping(
            self.reference_base_fees_wei,
            label="reference_base_fees_wei",
            allow_zero=False,
        )
        _require_resource_mapping(
            self.elasticities,
            label="elasticities",
            allow_zero=True,
        )

    def quantities(
        self,
        base_fees_wei: Mapping[str, float],
    ) -> dict[str, float]:
        _require_resource_mapping(
            base_fees_wei,
            label="base_fees_wei",
            allow_zero=False,
        )
        return {
            resource: float(self.anchor_metered_gas[resource])
            * (
                float(base_fees_wei[resource])
                / float(self.reference_base_fees_wei[resource])
            )
            ** (-float(self.elasticities[resource]))
            for resource in DEMAND_RESOURCES
        }


@dataclass(frozen=True)
class BundlePriced7999Demand:
    """Bundle-priced execution, static-data, state, and induced-BAL demand.

    The model follows publication notebook ``7999_equilibrium/03``. Execution and state activity respond to
    their own metered charge plus the data charge on runtime BAL generated by
    that activity. Static transaction data keeps the independently estimated
    data elasticity. Demand shocks shift execution activity, static data, and
    state creation; BAL has no independent shock and is derived from realized
    parent activity.

    With ``R_e = q_e / q_e0``::

        q_e = z_e q_e0 [
            (m_e b_e + w_e R_e ** (rho_A - 1) b_d) / p0
        ] ** (-eps_e)
        q_s = z_s q_s0 [
            (m_s b_s + w_s b_d) / p0
        ] ** (-eps_s)
        g_static = z_d g_static0 [m_d b_d / p0] ** (-eps_d)
        g_BAL = w_e q_e0 R_e ** rho_A + w_s q_s

    The execution equation is solved in log space when ``rho_A != 1``.
    """

    execution_quantity_anchor: float
    state_quantity_anchor: float
    static_data_gas_anchor: float
    historical_price_wei: float
    metering_multipliers: Mapping[str, float]
    elasticities: Mapping[str, float]
    bal_intensities: Mapping[str, float]
    rho_A: float = 1.0

    def __post_init__(self) -> None:
        positive_scalars = {
            "execution_quantity_anchor": self.execution_quantity_anchor,
            "state_quantity_anchor": self.state_quantity_anchor,
            "static_data_gas_anchor": self.static_data_gas_anchor,
            "historical_price_wei": self.historical_price_wei,
            "rho_A": self.rho_A,
        }
        for name, value in positive_scalars.items():
            if not math.isfinite(float(value)) or float(value) <= 0:
                raise ValueError(f"{name} must be finite and positive")
        _require_resource_mapping(
            self.metering_multipliers,
            label="metering_multipliers",
            allow_zero=False,
        )
        _require_resource_mapping(
            self.elasticities,
            label="elasticities",
            allow_zero=True,
        )
        for resource in ("execution", "state"):
            if resource not in self.bal_intensities:
                raise ValueError(f"bal_intensities is missing {resource!r}")
            value = float(self.bal_intensities[resource])
            if not math.isfinite(value) or value < 0:
                raise ValueError(
                    f"bal_intensities[{resource!r}] must be finite and " "non-negative"
                )
        # This condition makes the log-space execution residual strictly
        # increasing for every possible split between execution and BAL cost.
        eps_execution = float(self.elasticities["execution"])
        if 1.0 + eps_execution * (float(self.rho_A) - 1.0) <= 0:
            raise ValueError(
                "rho_A and execution elasticity imply a non-monotone "
                "execution equation"
            )

    @staticmethod
    def _logsumexp_pair(left: float, right: float) -> float:
        if left == -math.inf:
            return right
        if right == -math.inf:
            return left
        maximum = max(left, right)
        return maximum + math.log(math.exp(left - maximum) + math.exp(right - maximum))

    @staticmethod
    def _validated_shocks(
        shocks: Mapping[str, float] | None,
    ) -> dict[str, float]:
        values = (
            {resource: 1.0 for resource in DEMAND_RESOURCES}
            if shocks is None
            else {resource: float(shocks[resource]) for resource in DEMAND_RESOURCES}
        )
        _require_resource_mapping(values, label="shocks", allow_zero=False)
        # The access-composition residual is optional and defaults to one.  It
        # records how access-heavy a block is for its parent activity, which
        # the parent demand curves cannot express.
        access = 1.0 if shocks is None else float(shocks.get("access", 1.0))
        if not math.isfinite(access) or access <= 0:
            raise ValueError("shocks['access'] must be finite and positive")
        values["access"] = access
        return values

    def _execution_log_ratio(
        self,
        *,
        execution_base_fee_wei: float,
        data_base_fee_wei: float,
        execution_shock: float,
    ) -> float:
        elasticity = float(self.elasticities["execution"])
        multiplier = float(self.metering_multipliers["execution"])
        intensity = float(self.bal_intensities["execution"])
        rho_A = float(self.rho_A)
        historical_price = float(self.historical_price_wei)

        log_execution_charge = math.log(multiplier * execution_base_fee_wei)
        log_bal_charge_constant = (
            -math.inf if intensity == 0 else math.log(intensity * data_base_fee_wei)
        )
        log_historical_price = math.log(historical_price)
        log_shock = math.log(execution_shock)

        def residual(log_ratio: float) -> float:
            log_parent_price = self._logsumexp_pair(
                log_execution_charge,
                log_bal_charge_constant + (rho_A - 1.0) * log_ratio,
            )
            return (
                log_ratio
                - log_shock
                + elasticity * (log_parent_price - log_historical_price)
            )

        if math.isclose(rho_A, 1.0, rel_tol=0.0, abs_tol=1e-15):
            log_parent_price = self._logsumexp_pair(
                log_execution_charge, log_bal_charge_constant
            )
            return log_shock - elasticity * (log_parent_price - log_historical_price)

        low, high = -80.0, 80.0
        low_value, high_value = residual(low), residual(high)
        if low_value > 0 or high_value < 0:
            raise RuntimeError(
                "could not bracket the implicit execution-demand solution"
            )
        for _ in range(160):
            middle = 0.5 * (low + high)
            value = residual(middle)
            if value > 0:
                high = middle
            else:
                low = middle
        return 0.5 * (low + high)

    def evaluate_with_shocks(
        self,
        base_fees_wei: Mapping[str, float],
        shocks: Mapping[str, float] | None = None,
    ) -> BundleDemandEvaluation:
        _require_resource_mapping(
            base_fees_wei,
            label="base_fees_wei",
            allow_zero=False,
        )
        shock = self._validated_shocks(shocks)
        b_execution = float(base_fees_wei["execution"])
        b_data = float(base_fees_wei["data"])
        b_state = float(base_fees_wei["state"])

        log_execution_ratio = self._execution_log_ratio(
            execution_base_fee_wei=b_execution,
            data_base_fee_wei=b_data,
            execution_shock=shock["execution"],
        )
        execution_ratio = math.exp(log_execution_ratio)
        effective_execution_bal_intensity = float(
            self.bal_intensities["execution"]
        ) * execution_ratio ** (float(self.rho_A) - 1.0)
        execution_parent_price = (
            float(self.metering_multipliers["execution"]) * b_execution
            + effective_execution_bal_intensity * b_data
        )
        state_parent_price = (
            float(self.metering_multipliers["state"]) * b_state
            + float(self.bal_intensities["state"]) * b_data
        )

        q_execution = float(self.execution_quantity_anchor) * execution_ratio
        q_state = (
            float(self.state_quantity_anchor)
            * shock["state"]
            * (state_parent_price / float(self.historical_price_wei))
            ** (-float(self.elasticities["state"]))
        )
        static_data = (
            float(self.static_data_gas_anchor)
            * shock["data"]
            * (
                float(self.metering_multipliers["data"])
                * b_data
                / float(self.historical_price_wei)
            )
            ** (-float(self.elasticities["data"]))
        )
        # The access residual scales realized BAL only.  It is composition news
        # rather than an anticipated intensity, so it does not enter the parent
        # price that the demand curves were evaluated at.
        access_shock = shock["access"]
        execution_bal = (
            float(self.bal_intensities["execution"])
            * float(self.execution_quantity_anchor)
            * execution_ratio ** float(self.rho_A)
            * access_shock
        )
        state_bal = float(self.bal_intensities["state"]) * q_state * access_shock
        offered = {
            "execution": float(self.metering_multipliers["execution"]) * q_execution,
            "data": static_data + execution_bal + state_bal,
            "state": float(self.metering_multipliers["state"]) * q_state,
        }
        return BundleDemandEvaluation(
            offered_gas=offered,
            parent_quantities={
                "execution": q_execution,
                "state": q_state,
            },
            parent_prices_wei={
                "execution": execution_parent_price,
                "state": state_parent_price,
            },
            static_data_gas=static_data,
            execution_bal_gas=execution_bal,
            state_bal_gas=state_bal,
            effective_execution_bal_intensity=(effective_execution_bal_intensity),
            access_shock=access_shock,
        )

    def quantities_with_shocks(
        self,
        base_fees_wei: Mapping[str, float],
        shocks: Mapping[str, float],
    ) -> dict[str, float]:
        return dict(self.evaluate_with_shocks(base_fees_wei, shocks).offered_gas)

    def quantities(
        self,
        base_fees_wei: Mapping[str, float],
    ) -> dict[str, float]:
        return dict(self.evaluate_with_shocks(base_fees_wei).offered_gas)


@dataclass(frozen=True)
class ElasticityMatrixDemand:
    """Constant-elasticity demand with explicit cross-price responses.

    The matrix entry ``matrix[i][j]`` is ``d log(q_i) / d log(p_j)``.
    Diagonal entries are normally negative.  A negative off-diagonal entry
    represents bundle complementarity: raising fee ``j`` removes some of
    resource ``i`` carried by the same transactions.  A positive entry
    represents substitution.
    """

    anchor_metered_gas: Mapping[str, float]
    reference_base_fees_wei: Mapping[str, float]
    matrix: Mapping[str, Mapping[str, float]]

    def __post_init__(self) -> None:
        _require_resource_mapping(
            self.anchor_metered_gas,
            label="anchor_metered_gas",
            allow_zero=False,
        )
        _require_resource_mapping(
            self.reference_base_fees_wei,
            label="reference_base_fees_wei",
            allow_zero=False,
        )
        for demand_resource in DEMAND_RESOURCES:
            if demand_resource not in self.matrix:
                raise ValueError(f"matrix is missing row {demand_resource!r}")
            row = self.matrix[demand_resource]
            for price_resource in DEMAND_RESOURCES:
                if price_resource not in row:
                    raise ValueError(
                        "matrix is missing entry "
                        f"[{demand_resource!r}][{price_resource!r}]"
                    )
                if not math.isfinite(float(row[price_resource])):
                    raise ValueError("matrix entries must be finite")

    @classmethod
    def from_independent(
        cls,
        *,
        anchor_metered_gas: Mapping[str, float],
        reference_base_fees_wei: Mapping[str, float],
        elasticities: Mapping[str, float],
    ) -> "ElasticityMatrixDemand":
        _require_resource_mapping(
            elasticities,
            label="elasticities",
            allow_zero=True,
        )
        matrix = {
            i: {j: -float(elasticities[i]) if i == j else 0.0 for j in DEMAND_RESOURCES}
            for i in DEMAND_RESOURCES
        }
        return cls(
            anchor_metered_gas=anchor_metered_gas,
            reference_base_fees_wei=reference_base_fees_wei,
            matrix=matrix,
        )

    def quantities(
        self,
        base_fees_wei: Mapping[str, float],
    ) -> dict[str, float]:
        _require_resource_mapping(
            base_fees_wei,
            label="base_fees_wei",
            allow_zero=False,
        )
        ratios = {
            resource: float(base_fees_wei[resource])
            / float(self.reference_base_fees_wei[resource])
            for resource in DEMAND_RESOURCES
        }
        output: dict[str, float] = {}
        for demand_resource in DEMAND_RESOURCES:
            log_quantity = math.log(float(self.anchor_metered_gas[demand_resource]))
            for price_resource in DEMAND_RESOURCES:
                log_quantity += float(
                    self.matrix[demand_resource][price_resource]
                ) * math.log(ratios[price_resource])
            output[demand_resource] = math.exp(log_quantity)
        return output
